# Generated by Django 3.0.3 on 2020-02-12 19:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('custom_user', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='mycustomuser',
            name='favorite_color',
            field=models.CharField(default='purple', max_length=20),
            preserve_default=False,
        ),
    ]
