# Generated by Django 3.0.3 on 2020-02-12 20:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('custom_user', '0002_mycustomuser_favorite_color'),
    ]

    operations = [
        migrations.AddField(
            model_name='mycustomuser',
            name='age',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='mycustomuser',
            name='display_name',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='mycustomuser',
            name='homepage',
            field=models.URLField(null=True),
        ),
    ]
